### ISSUE TITLE
Learn-Settings 

### ISSUE THREAD

**Issue by Agreon** [Agreon/Taggit#2]
**TODOS**
- [x] Show progress of current LearnObject

**Bugs**
- [ ] Responsiveness: Both Buttons should be in one row

**NiveToHave**
- [ ] Add Questions, that are not in Document
- [ ] Order Questions By..
- [ ] Show Answer of Questions  on Some-Click
- [ ] Show More Information at Add-Tag (only with 2 inputs e.g.)
- [ ] Reset All of Type
- [ ] Show level-labels in diffrent colors
