### ISSUE TITLE
Learn-Page

### ISSUE THREAD

**Issue by Agreon** [Agreon/Taggit#3]
### TODOs
- [ ] Progress-Bar is sometimes not showing correct progress
- [ ] Evaluate which buttons to use

**Responsiveness**
- [ ] Flashcard should have less margin in small view 

**NiceToHave**
- [ ] Flashcard-Animation

### Further Stuff
* Maybe show the given Answer
